/**:
  ros__parameters:
    debug: false
    vehicle_ip: '127.0.0.1:14550'
    timeout: 15
    mission_filename: "MisionesLoyola_dron_2.kml"

mqtt_node:
  ros__parameters:
    vehicle_id: 1
    mqtt_addr: 20.126.131.210

sensor_module_node:
  ros__parameters:
    database_name: "LOCAL_DATABASE.db"
    USB_string: "USBPort1"
    timeout: 6
    baudrate: 115200
    pump_parameters:
      charging_time: 7
      discharging_time: 2
      serial_string: "/dev/ttyACM0"
      mode: "BuiltInPin"