/**:
  ros__parameters:
    debug: false
    vehicle_ip: "tcp:navio.local:5678"
    timeout: 15
    mission_filename: "MisionesLoyola_dron_2.kml"
    vehicle_id: 1
    mqtt_addr: 127.0.0.1
    pump: false
    num_samples: 4