/**:
  ros__parameters:
    debug: true
    vehicle_ip: "tcp:navio.local:5678"
    debug_vehicle_ip: "127.0.0.1:14550"
    timeout: 15
    mission_filename: "MisionesLoyola_dron_2.kml"
    vehicle_id: 3
    mqtt_addr: "bender.us.es"
    mqtt_user: "asv1"
    mqtt_password: "azkenmuga"
    num_samples: 4
    time_between_samples: 0.5
    travelling_timeout: 60
    arm_timeout: 15
    max_distance: 5000
    connect_timeout: 15
    simple_goto_timeout: 10
    internet_loss_timeout: 30
    sensor_read_timeout: 15
    sonar_connection_type: "USB"
