/**:
  ros__parameters:
    debug: True
    vehicle_ip: "tcp:192.168.1.203:5678" 
    debug_vehicle_ip: "127.0.0.1:14550"
    timeout: 15
    mission_filename: "MisionesLoyola_dron_2.kml"
    mqtt_addr: "bender.us.es"
    mqtt_password: "azkenmuga"
    database_host: "golem.us.es"
    database_port: 6006
    database_user : "root"
    database_password : "azkenmugaÑ."
    database_db : "ASV_US"
    num_samples: 4
    time_between_samples: 0.5
    travelling_timeout: 60
    arm_timeout: 15
    max_distance: 5000
    connect_timeout: 15
    simple_goto_timeout: 60
    internet_loss_timeout: 30
    sensor_read_timeout: 15
    sonar_connection_type: "USB"
    sonar_device_name: "/dev/SONAR"
