title: ASVs for Environmental Monitoring
description: Documentación técnica de software y hardware.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root.