name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image (ARM)
      run: docker build . --file dockerfile_ARM --tag syanes/asv_us:arm64 --platform linux/arm64

    - name: Push the Docker image (ARM)
      run: docker push dockerfile_ARM --tag syanes/asv_us:arm64
