name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-18.04
    env:       
      DOCKER_IMAGE: syanes/asv_us:arm64     
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      DOCKER_TARGET_PLATFORM: linux/arm/v8
      
    steps:
    - name: Checkout de code
    - uses: actions/checkout@v3

    - name: Docker Login      
      if: success()      
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    
    - name: Build the Docker image (ARM)
      run: |
        docker build . --file dockerfile_ARM --tag syanes/asv_us:arm64 --platform ${DOCKER_TARGET_PLATFORM}

    - name: Push the Docker image (ARM)
      run: |
        docker push dockerfile_ARM --tag ${DOCKER_IMAGE}
